# Generated by Django 6.0.5 on 2026-05-19 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_side', '0004_alter_studentprofile_commitment_and_more'),
        ('teacher_side', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_csv', models.TextField(help_text='Verbatim CSV uploaded for this session (audit + replay).')),
                ('min_size', models.IntegerField(help_text='Minimum allowed team size.')),
                ('max_size', models.IntegerField(help_text='Maximum allowed team size.')),
                ('weights', models.JSONField(help_text='Named-dict form of the fitness weights; see WEIGHT_KEYS for canonical order.')),
                ('target_col', models.CharField(default='teams', help_text='Column name in the CSV where team labels are written.', max_length=50)),
                ('column_order', models.JSONField(default=list, help_text='Canonical CSV column order; jsonb-safe alternative to dict key order.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rematch_token', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('rematch_started_at', models.DateTimeField(blank=True, null=True)),
                ('rematch_cancel_requested', models.BooleanField(default=False)),
                ('template_used', models.ForeignKey(blank=True, help_text='Team name template used for this session, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher_side.teamnametemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_locked', models.BooleanField(default=False, help_text='When True, membership is frozen: moves in/out are rejected and the team is excluded from re-match.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='teacher_side.matchingsession')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('session', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RematchAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_pk_snapshot', models.IntegerField(help_text='MatchingSession PK at row creation; survives session deletion.')),
                ('token', models.CharField(db_index=True, max_length=36)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('cancelled', 'Cancelled'), ('error', 'Error'), ('worker_died', 'Worker died'), ('rejected', 'Rejected (already running)'), ('client_disconnect', 'Client disconnect'), ('noop', 'No-op (degraded)')], db_index=True, default='running', max_length=20)),
                ('generations_completed', models.IntegerField(default=0)),
                ('students_moved', models.IntegerField(default=0)),
                ('teams_created', models.IntegerField(default=0)),
                ('weights_snapshot', models.JSONField(default=dict)),
                ('error_class', models.CharField(blank=True, max_length=200)),
                ('error_message', models.TextField(blank=True)),
                ('db_vendor', models.CharField(blank=True, max_length=20)),
                ('worker_pid', models.IntegerField(blank=True, null=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rematch_audit_logs', to='teacher_side.matchingsession')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['session', '-started_at'], name='teacher_sid_session_de8a0f_idx'), models.Index(fields=['outcome', '-started_at'], name='teacher_sid_outcome_1a7421_idx'), models.Index(fields=['token'], name='teacher_sid_token_156eab_idx')],
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('original_row', models.JSONField(help_text='Snapshot of all CSV columns at session creation, string-coerced.')),
                ('is_locked', models.BooleanField(default=False, help_text='Locked memberships reject moves and are excluded from re-match.')),
                ('profile', models.ForeignKey(blank=True, help_text='Soft link by username; survives profile deletion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_memberships', to='student_side.studentprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='teacher_side.matchingsession')),
                ('team', models.ForeignKey(blank=True, help_text='Null = unassigned pool.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='teacher_side.team')),
            ],
            options={
                'ordering': ['username'],
                'unique_together': {('session', 'username')},
            },
        ),
    ]
