# Generated by Django 5.2.8 on 2026-05-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_side", "0003_rename_name_studentprofile_student_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="commitment",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="experience_level",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="gender",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="lead_preference",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
